In [1]:
!unzip '/content/drive/MyDrive/birds.zip'

Archive:  /content/drive/MyDrive/birds.zip
  inflating: test_data/test_data/blasti/DSC_6396.jpg  
  inflating: test_data/test_data/blasti/DSC_6397.jpg  
  inflating: test_data/test_data/blasti/DSC_6398.jpg  
  inflating: test_data/test_data/blasti/DSC_6399.jpg  
  inflating: test_data/test_data/blasti/DSC_6400.jpg  
  inflating: test_data/test_data/blasti/DSC_6401.jpg  
  inflating: test_data/test_data/blasti/DSC_6402.jpg  
  inflating: test_data/test_data/blasti/DSC_6403.jpg  
  inflating: test_data/test_data/blasti/DSC_6405.jpg  
  inflating: test_data/test_data/blasti/DSC_6406.jpg  
  inflating: test_data/test_data/blasti/DSC_6407.jpg  
  inflating: test_data/test_data/blasti/DSC_6408.jpg  
  inflating: test_data/test_data/blasti/DSC_6409.jpg  
  inflating: test_data/test_data/blasti/DSC_6410.jpg  
  inflating: test_data/test_data/blasti/DSC_6411.jpg  
  inflating: test_data/test_data/bonegl/DSC_4587.jpg  
  inflating: test_data/test_data/bonegl/DSC_4588.jpg  
  inflating: test_data

In [ ]:
#Data augmentation


In [3]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [4]:
train_gen = ImageDataGenerator(rescale=(1./255),horizontal_flip=True,shear_range=0.2)
test_gen = ImageDataGenerator(rescale=(1./255))

In [5]:
train = train_gen.flow_from_directory('/content/train_data/train_data',
                                      target_size=(120,120),
                                      class_mode='categorical',
                                      batch_size=8
                                      )
test = test_gen.flow_from_directory('/content/test_data/test_data',
                                     target_size=(120,120),
                                     class_mode='categorical',
                                     batch_size=8
                                     )

Found 150 images belonging to 16 classes.
Found 157 images belonging to 16 classes.


In [6]:
train.class_indices

{'blasti': 0,
 'bonegl': 1,
 'brhkyt': 2,
 'cbrtsh': 3,
 'cmnmyn': 4,
 'gretit': 5,
 'hilpig': 6,
 'himbul': 7,
 'himgri': 8,
 'hsparo': 9,
 'indvul': 10,
 'jglowl': 11,
 'lbicrw': 12,
 'mgprob': 13,
 'rebimg': 14,
 'wcrsrt': 15}

In [7]:
#CNN Model
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense
from tensorflow.keras.models import Sequential

In [8]:
model = Sequential()
model.add(Convolution2D(20,(3,3),activation='relu',input_shape=(120,120,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(45,activation='relu'))
model.add(Dense(16,activation='softmax'))

In [9]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [10]:
model.fit(train,batch_size=8,validation_data=test,epochs=10)

Epoch 1/10
19/19 [==============================] - 78s 4s/step - loss: 3.6885 - accuracy: 0.0733 - val_loss: 2.7718 - val_accuracy: 0.1210
Epoch 2/10
19/19 [==============================] - 69s 4s/step - loss: 2.7713 - accuracy: 0.1200 - val_loss: 2.7702 - val_accuracy: 0.1210
Epoch 3/10
19/19 [==============================] - 70s 4s/step - loss: 2.7825 - accuracy: 0.1200 - val_loss: 2.7644 - val_accuracy: 0.1019
Epoch 4/10
19/19 [==============================] - 70s 4s/step - loss: 2.7665 - accuracy: 0.1200 - val_loss: 2.7665 - val_accuracy: 0.1210
Epoch 5/10
19/19 [==============================] - 69s 4s/step - loss: 2.7871 - accuracy: 0.1200 - val_loss: 2.7644 - val_accuracy: 0.1210
Epoch 6/10
19/19 [==============================] - 70s 4s/step - loss: 2.7632 - accuracy: 0.1200 - val_loss: 2.7623 - val_accuracy: 0.1210
Epoch 7/10
19/19 [==============================] - 70s 4s/step - loss: 2.7609 - accuracy: 0.1200 - val_loss: 2.7604 - val_accuracy: 0.1210
Epoch 8/10
19/19 [==

In [11]:
model.save('birdWeights.h5')

In [12]:
#Testing

In [15]:
import numpy as np
from tensorflow.keras.preprocessing import image

In [16]:
img = image.load_img('/content/crow.jpeg', target_size=(120,120))

In [17]:
img = image.img_to_array(img)
img 

array([[[179., 177., 154.],
        [181., 179., 156.],
        [182., 180., 155.],
        ...,
        [122., 120., 108.],
        [122., 120., 108.],
        [123., 119., 108.]],

       [[180., 178., 153.],
        [180., 178., 153.],
        [182., 180., 155.],
        ...,
        [124., 122., 110.],
        [124., 122., 110.],
        [125., 121., 110.]],

       [[179., 177., 152.],
        [180., 178., 153.],
        [179., 177., 152.],
        ...,
        [126., 124., 112.],
        [125., 123., 111.],
        [125., 123., 111.]],

       ...,

       [[ 84.,  77.,  71.],
        [ 85.,  78.,  72.],
        [ 86.,  79.,  73.],
        ...,
        [181., 189., 191.],
        [183., 191., 193.],
        [182., 188., 188.]],

       [[ 84.,  77.,  71.],
        [ 84.,  79.,  73.],
        [ 88.,  81.,  75.],
        ...,
        [183., 189., 189.],
        [178., 183., 186.],
        [159., 166., 172.]],

       [[ 83.,  75.,  72.],
        [ 85.,  77.,  74.],
        [ 88.,  

In [18]:
img=np.expand_dims(img,axis=0)
img

array([[[[179., 177., 154.],
         [181., 179., 156.],
         [182., 180., 155.],
         ...,
         [122., 120., 108.],
         [122., 120., 108.],
         [123., 119., 108.]],

        [[180., 178., 153.],
         [180., 178., 153.],
         [182., 180., 155.],
         ...,
         [124., 122., 110.],
         [124., 122., 110.],
         [125., 121., 110.]],

        [[179., 177., 152.],
         [180., 178., 153.],
         [179., 177., 152.],
         ...,
         [126., 124., 112.],
         [125., 123., 111.],
         [125., 123., 111.]],

        ...,

        [[ 84.,  77.,  71.],
         [ 85.,  78.,  72.],
         [ 86.,  79.,  73.],
         ...,
         [181., 189., 191.],
         [183., 191., 193.],
         [182., 188., 188.]],

        [[ 84.,  77.,  71.],
         [ 84.,  79.,  73.],
         [ 88.,  81.,  75.],
         ...,
         [183., 189., 189.],
         [178., 183., 186.],
         [159., 166., 172.]],

        [[ 83.,  75.,  72.],
       

In [19]:
model.predict(img)

1/1 [==============================] - 0s 79ms/step


array([[0.06634858, 0.05995996, 0.05910679, 0.06060239, 0.0612994 ,
        0.06038553, 0.0638299 , 0.06857152, 0.06715105, 0.06311535,
        0.06294928, 0.06007016, 0.06009601, 0.05986032, 0.06367163,
        0.06298219]], dtype=float32)

In [20]:
np.argmax(model.predict(img))

1/1 [==============================] - 0s 25ms/step


7

In [21]:
# Testing 1
img1 = image.load_img('/content/owl.jpeg',target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
pred = np.argmax(model.predict(img1))
print(pred)

1/1 [==============================] - 0s 21ms/step
7


In [22]:
# Testing 2
img2 = image.load_img('/content/crow.jpeg',target_size=(120,120))
img2 = image.img_to_array(img2)
img2 = np.expand_dims(img2,axis=0)
pred = np.argmax(model.predict(img2))
print(pred)

1/1 [==============================] - 0s 22ms/step
7


In [23]:
# Testing 3
img3 = image.load_img('/content/pigeon.jpg',target_size=(120,120))
img3 = image.img_to_array(img3)
img3 = np.expand_dims(img3,axis=0)
pred = np.argmax(model.predict(img3))
print(pred)

1/1 [==============================] - 0s 19ms/step
7


In [ ]:
# Model Tuning (Adding feature extraction layers)

In [24]:
model = Sequential()
model.add(Convolution2D(12,(3,3),activation='relu',input_shape=(120, 120, 3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(24,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(36,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(62,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(16,activation='softmax'))

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 118, 118, 12)      336       
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 59, 59, 12)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 57, 57, 24)        2616      
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 28, 28, 24)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 26, 26, 36)        7812      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 13, 13, 36)      

In [26]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [29]:
model.fit(train,batch_size=8,validation_data=test,epochs=50)

Epoch 1/50
19/19 [==============================] - 72s 4s/step - loss: 0.0190 - accuracy: 1.0000 - val_loss: 7.4758 - val_accuracy: 0.3185
Epoch 2/50
19/19 [==============================] - 71s 4s/step - loss: 0.0124 - accuracy: 1.0000 - val_loss: 7.4430 - val_accuracy: 0.3248
Epoch 3/50
19/19 [==============================] - 69s 4s/step - loss: 0.0078 - accuracy: 1.0000 - val_loss: 7.6477 - val_accuracy: 0.3248
Epoch 4/50
19/19 [==============================] - 72s 4s/step - loss: 0.0059 - accuracy: 1.0000 - val_loss: 7.8188 - val_accuracy: 0.3185
Epoch 5/50
19/19 [==============================] - 70s 4s/step - loss: 0.0092 - accuracy: 1.0000 - val_loss: 7.8612 - val_accuracy: 0.3312
Epoch 6/50
19/19 [==============================] - 69s 4s/step - loss: 0.0074 - accuracy: 1.0000 - val_loss: 8.0244 - val_accuracy: 0.3312
Epoch 7/50
19/19 [==============================] - 69s 4s/step - loss: 0.0048 - accuracy: 1.0000 - val_loss: 8.1521 - val_accuracy: 0.3376
Epoch 8/50
19/19 [==

In [30]:
# Testing 1
img1 = image.load_img('/content/owl.jpeg',target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
pred = np.argmax(model.predict(img1))
print(pred)

1/1 [==============================] - 0s 77ms/step
7


In [31]:
# Testing 2
img2 = image.load_img('/content/crow.jpeg',target_size=(120,120))
img2 = image.img_to_array(img2)
img2 = np.expand_dims(img2,axis=0)
pred = np.argmax(model.predict(img2))
print(pred)

1/1 [==============================] - 0s 19ms/step
7


In [32]:
# Testing 3
img3 = image.load_img('/content/pigeon.jpg',target_size=(120,120))
img3 = image.img_to_array(img3)
img3 = np.expand_dims(img3,axis=0)
pred = np.argmax(model.predict(img3))
print(pred)

1/1 [==============================] - 0s 32ms/step
5


In [33]:
# Model tuning (with dropout, batch normalization & early stopping)

In [34]:
from tensorflow.keras.layers import BatchNormalization, Dropout

In [35]:
model = Sequential()
model.add(Convolution2D(12,(3,3),activation='relu',input_shape=(120, 120, 3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Convolution2D(24,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Convolution2D(36,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(62,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(16,activation='softmax'))

In [36]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 118, 118, 12)      336       
                                                                 
 batch_normalization (BatchN  (None, 118, 118, 12)     48        
 ormalization)                                                   
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 59, 59, 12)       0         
 2D)                                                             
                                                                 
 dropout (Dropout)           (None, 59, 59, 12)        0         
                                                                 
 conv2d_5 (Conv2D)           (None, 57, 57, 24)        2616      
                                                                 
 batch_normalization_1 (Batc  (None, 57, 57, 24)      

In [37]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [38]:
from tensorflow.keras.callbacks import EarlyStopping

In [39]:
early_stop = EarlyStopping(monitor='accuracy',patience=8)

In [ ]:
model.fit(train,batch_size=8,validation_data=test,epochs=50,callbacks=early_stop)

Epoch 1/50
19/19 [==============================] - 75s 4s/step - loss: 2.9016 - accuracy: 0.1067 - val_loss: 2.8381 - val_accuracy: 0.1338
Epoch 2/50
19/19 [==============================] - 72s 4s/step - loss: 2.4943 - accuracy: 0.2400 - val_loss: 3.1504 - val_accuracy: 0.0955
Epoch 3/50
19/19 [==============================] - 71s 4s/step - loss: 2.3605 - accuracy: 0.2867 - val_loss: 3.3466 - val_accuracy: 0.0955


In [ ]:
# Testing 1
img1 = image.load_img('/content/owl.jpeg',target_size=(120,120))
img1 = image.img_to_array(img1)
img1 = np.expand_dims(img1,axis=0)
pred = np.argmax(model.predict(img1))
print(pred)

In [ ]:
# Testing 2
img2 = image.load_img('/content/crow.jpeg',target_size=(120,120))
img2 = image.img_to_array(img2)
img2 = np.expand_dims(img2,axis=0)
pred = np.argmax(model.predict(img2))
print(pred)

In [ ]:
# Testing 3
img3 = image.load_img('/content/pigeon.jpg',target_size=(120,120))
img3 = image.img_to_array(img3)
img3 = np.expand_dims(img3,axis=0)
pred = np.argmax(model.predict(img3))
print(pred)